<?php
/**
 * InvoicesApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Tns\\EpayPolicy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * epay3 API 1.0
 *
 * This API supports the processing of credit card and eCheck/ACH payments.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@epay3.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Tns\\EpayPolicy\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Tns\\EpayPolicy\ApiException;
use Tns\\EpayPolicy\Configuration;
use Tns\\EpayPolicy\HeaderSelector;
use Tns\\EpayPolicy\ObjectSerializer;

/**
 * InvoicesApi Class Doc Comment
 *
 * @category Class
 * @package  Tns\\EpayPolicy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InvoicesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'invoicesEmail' => [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded',
        ],
        'invoicesGet' => [
            'application/json',
        ],
        'invoicesPayments' => [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded',
        ],
        'invoicesUpdate' => [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml',
            'application/x-www-form-urlencoded',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation invoicesEmail
     *
     * Sends an email for a collection of invoices in the management system.
     *
     * @param  \Tns\\EpayPolicy\Model\PostSendInvoiceEmailRequestModel $post_send_invoice_email_request_model The Invoice lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesEmail'] to see the possible values for this operation
     *
     * @throws \Tns\\EpayPolicy\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function invoicesEmail($post_send_invoice_email_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesEmail'][0])
    {
        $this->invoicesEmailWithHttpInfo($post_send_invoice_email_request_model, $impersonation_account_key, $contentType);
    }

    /**
     * Operation invoicesEmailWithHttpInfo
     *
     * Sends an email for a collection of invoices in the management system.
     *
     * @param  \Tns\\EpayPolicy\Model\PostSendInvoiceEmailRequestModel $post_send_invoice_email_request_model The Invoice lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesEmail'] to see the possible values for this operation
     *
     * @throws \Tns\\EpayPolicy\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function invoicesEmailWithHttpInfo($post_send_invoice_email_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesEmail'][0])
    {
        $request = $this->invoicesEmailRequest($post_send_invoice_email_request_model, $impersonation_account_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation invoicesEmailAsync
     *
     * Sends an email for a collection of invoices in the management system.
     *
     * @param  \Tns\\EpayPolicy\Model\PostSendInvoiceEmailRequestModel $post_send_invoice_email_request_model The Invoice lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoicesEmailAsync($post_send_invoice_email_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesEmail'][0])
    {
        return $this->invoicesEmailAsyncWithHttpInfo($post_send_invoice_email_request_model, $impersonation_account_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoicesEmailAsyncWithHttpInfo
     *
     * Sends an email for a collection of invoices in the management system.
     *
     * @param  \Tns\\EpayPolicy\Model\PostSendInvoiceEmailRequestModel $post_send_invoice_email_request_model The Invoice lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoicesEmailAsyncWithHttpInfo($post_send_invoice_email_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesEmail'][0])
    {
        $returnType = '';
        $request = $this->invoicesEmailRequest($post_send_invoice_email_request_model, $impersonation_account_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoicesEmail'
     *
     * @param  \Tns\\EpayPolicy\Model\PostSendInvoiceEmailRequestModel $post_send_invoice_email_request_model The Invoice lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesEmail'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function invoicesEmailRequest($post_send_invoice_email_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesEmail'][0])
    {

        // verify the required parameter 'post_send_invoice_email_request_model' is set
        if ($post_send_invoice_email_request_model === null || (is_array($post_send_invoice_email_request_model) && count($post_send_invoice_email_request_model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $post_send_invoice_email_request_model when calling invoicesEmail'
            );
        }



        $resourcePath = '/api/v1/Invoices/Email';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($impersonation_account_key !== null) {
            $headerParams['impersonationAccountKey'] = ObjectSerializer::toHeaderValue($impersonation_account_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($post_send_invoice_email_request_model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($post_send_invoice_email_request_model));
            } else {
                $httpBody = $post_send_invoice_email_request_model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation invoicesGet
     *
     * Gets a collection of invoices given lookup attributes. Add these attributes as individual parameters.
     *
     * @param  string $impersonation_account_key impersonation_account_key (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesGet'] to see the possible values for this operation
     *
     * @throws \Tns\\EpayPolicy\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function invoicesGet($impersonation_account_key = null, string $contentType = self::contentTypes['invoicesGet'][0])
    {
        $this->invoicesGetWithHttpInfo($impersonation_account_key, $contentType);
    }

    /**
     * Operation invoicesGetWithHttpInfo
     *
     * Gets a collection of invoices given lookup attributes. Add these attributes as individual parameters.
     *
     * @param  string $impersonation_account_key (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesGet'] to see the possible values for this operation
     *
     * @throws \Tns\\EpayPolicy\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function invoicesGetWithHttpInfo($impersonation_account_key = null, string $contentType = self::contentTypes['invoicesGet'][0])
    {
        $request = $this->invoicesGetRequest($impersonation_account_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation invoicesGetAsync
     *
     * Gets a collection of invoices given lookup attributes. Add these attributes as individual parameters.
     *
     * @param  string $impersonation_account_key (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoicesGetAsync($impersonation_account_key = null, string $contentType = self::contentTypes['invoicesGet'][0])
    {
        return $this->invoicesGetAsyncWithHttpInfo($impersonation_account_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoicesGetAsyncWithHttpInfo
     *
     * Gets a collection of invoices given lookup attributes. Add these attributes as individual parameters.
     *
     * @param  string $impersonation_account_key (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoicesGetAsyncWithHttpInfo($impersonation_account_key = null, string $contentType = self::contentTypes['invoicesGet'][0])
    {
        $returnType = '';
        $request = $this->invoicesGetRequest($impersonation_account_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoicesGet'
     *
     * @param  string $impersonation_account_key (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function invoicesGetRequest($impersonation_account_key = null, string $contentType = self::contentTypes['invoicesGet'][0])
    {



        $resourcePath = '/api/v1/Invoices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($impersonation_account_key !== null) {
            $headerParams['impersonationAccountKey'] = ObjectSerializer::toHeaderValue($impersonation_account_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation invoicesPayments
     *
     * Updates a collection of invoices in the management system.
     *
     * @param  \Tns\\EpayPolicy\Model\UpdateInvoicesRequestModel $update_invoices_request_model The paid invoices and lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesPayments'] to see the possible values for this operation
     *
     * @throws \Tns\\EpayPolicy\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function invoicesPayments($update_invoices_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesPayments'][0])
    {
        $this->invoicesPaymentsWithHttpInfo($update_invoices_request_model, $impersonation_account_key, $contentType);
    }

    /**
     * Operation invoicesPaymentsWithHttpInfo
     *
     * Updates a collection of invoices in the management system.
     *
     * @param  \Tns\\EpayPolicy\Model\UpdateInvoicesRequestModel $update_invoices_request_model The paid invoices and lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesPayments'] to see the possible values for this operation
     *
     * @throws \Tns\\EpayPolicy\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function invoicesPaymentsWithHttpInfo($update_invoices_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesPayments'][0])
    {
        $request = $this->invoicesPaymentsRequest($update_invoices_request_model, $impersonation_account_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation invoicesPaymentsAsync
     *
     * Updates a collection of invoices in the management system.
     *
     * @param  \Tns\\EpayPolicy\Model\UpdateInvoicesRequestModel $update_invoices_request_model The paid invoices and lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesPayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoicesPaymentsAsync($update_invoices_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesPayments'][0])
    {
        return $this->invoicesPaymentsAsyncWithHttpInfo($update_invoices_request_model, $impersonation_account_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoicesPaymentsAsyncWithHttpInfo
     *
     * Updates a collection of invoices in the management system.
     *
     * @param  \Tns\\EpayPolicy\Model\UpdateInvoicesRequestModel $update_invoices_request_model The paid invoices and lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesPayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoicesPaymentsAsyncWithHttpInfo($update_invoices_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesPayments'][0])
    {
        $returnType = '';
        $request = $this->invoicesPaymentsRequest($update_invoices_request_model, $impersonation_account_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoicesPayments'
     *
     * @param  \Tns\\EpayPolicy\Model\UpdateInvoicesRequestModel $update_invoices_request_model The paid invoices and lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesPayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function invoicesPaymentsRequest($update_invoices_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesPayments'][0])
    {

        // verify the required parameter 'update_invoices_request_model' is set
        if ($update_invoices_request_model === null || (is_array($update_invoices_request_model) && count($update_invoices_request_model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_invoices_request_model when calling invoicesPayments'
            );
        }



        $resourcePath = '/api/v1/Invoices/Payments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($impersonation_account_key !== null) {
            $headerParams['impersonationAccountKey'] = ObjectSerializer::toHeaderValue($impersonation_account_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_invoices_request_model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_invoices_request_model));
            } else {
                $httpBody = $update_invoices_request_model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation invoicesUpdate
     *
     * Updates a collection of invoices in the management system.
     *
     * @param  string $api_version api_version (required)
     * @param  \Tns\\EpayPolicy\Model\UpdateInvoicesRequestModel $update_invoices_request_model The paid invoices and lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesUpdate'] to see the possible values for this operation
     *
     * @throws \Tns\\EpayPolicy\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     * @deprecated
     */
    public function invoicesUpdate($api_version, $update_invoices_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesUpdate'][0])
    {
        $this->invoicesUpdateWithHttpInfo($api_version, $update_invoices_request_model, $impersonation_account_key, $contentType);
    }

    /**
     * Operation invoicesUpdateWithHttpInfo
     *
     * Updates a collection of invoices in the management system.
     *
     * @param  string $api_version (required)
     * @param  \Tns\\EpayPolicy\Model\UpdateInvoicesRequestModel $update_invoices_request_model The paid invoices and lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesUpdate'] to see the possible values for this operation
     *
     * @throws \Tns\\EpayPolicy\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     * @deprecated
     */
    public function invoicesUpdateWithHttpInfo($api_version, $update_invoices_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesUpdate'][0])
    {
        $request = $this->invoicesUpdateRequest($api_version, $update_invoices_request_model, $impersonation_account_key, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation invoicesUpdateAsync
     *
     * Updates a collection of invoices in the management system.
     *
     * @param  string $api_version (required)
     * @param  \Tns\\EpayPolicy\Model\UpdateInvoicesRequestModel $update_invoices_request_model The paid invoices and lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function invoicesUpdateAsync($api_version, $update_invoices_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesUpdate'][0])
    {
        return $this->invoicesUpdateAsyncWithHttpInfo($api_version, $update_invoices_request_model, $impersonation_account_key, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoicesUpdateAsyncWithHttpInfo
     *
     * Updates a collection of invoices in the management system.
     *
     * @param  string $api_version (required)
     * @param  \Tns\\EpayPolicy\Model\UpdateInvoicesRequestModel $update_invoices_request_model The paid invoices and lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     * @deprecated
     */
    public function invoicesUpdateAsyncWithHttpInfo($api_version, $update_invoices_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesUpdate'][0])
    {
        $returnType = '';
        $request = $this->invoicesUpdateRequest($api_version, $update_invoices_request_model, $impersonation_account_key, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoicesUpdate'
     *
     * @param  string $api_version (required)
     * @param  \Tns\\EpayPolicy\Model\UpdateInvoicesRequestModel $update_invoices_request_model The paid invoices and lookup attributes. (required)
     * @param  string $impersonation_account_key The impersonation account key. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['invoicesUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     * @deprecated
     */
    public function invoicesUpdateRequest($api_version, $update_invoices_request_model, $impersonation_account_key = null, string $contentType = self::contentTypes['invoicesUpdate'][0])
    {

        // verify the required parameter 'api_version' is set
        if ($api_version === null || (is_array($api_version) && count($api_version) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $api_version when calling invoicesUpdate'
            );
        }

        // verify the required parameter 'update_invoices_request_model' is set
        if ($update_invoices_request_model === null || (is_array($update_invoices_request_model) && count($update_invoices_request_model) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_invoices_request_model when calling invoicesUpdate'
            );
        }



        $resourcePath = '/api/v1/Invoices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $api_version,
            'api-version', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);

        // header params
        if ($impersonation_account_key !== null) {
            $headerParams['impersonationAccountKey'] = ObjectSerializer::toHeaderValue($impersonation_account_key);
        }



        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_invoices_request_model)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_invoices_request_model));
            } else {
                $httpBody = $update_invoices_request_model;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
