<?php
/**
 * QuickQuoteModelTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Tns\EpayPolicy
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * epay3 API 1.0
 *
 * This API supports the processing of credit card and eCheck/ACH payments.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@epay3.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Tns\EpayPolicy\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * QuickQuoteModelTest Class Doc Comment
 *
 * @category    Class
 * @description QuickQuoteModel
 * @package     Tns\EpayPolicy
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class QuickQuoteModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "QuickQuoteModel"
     */
    public function testQuickQuoteModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "invoice_id"
     */
    public function testPropertyInvoiceId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_eligible"
     */
    public function testPropertyIsEligible()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "down_payment"
     */
    public function testPropertyDownPayment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "finance_ineligibility_reason"
     */
    public function testPropertyFinanceIneligibilityReason()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "number_of_installments"
     */
    public function testPropertyNumberOfInstallments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "installment_amount"
     */
    public function testPropertyInstallmentAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "exception"
     */
    public function testPropertyException()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "finance_eligibility_hash"
     */
    public function testPropertyFinanceEligibilityHash()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "finance_company_name"
     */
    public function testPropertyFinanceCompanyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
